services:
  mongo:
    image: mongo:7
    platform: linux/amd64
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    platform: linux/amd64
    container_name: backend
    environment:
      - MONGODB_CONNECTION=mongodb://admin:strongpassword@144.91.113.233:27017/admin?authSource=admin
      - SERVER_ADDRESS=http://localhost:1975
      - FRONTEND_URL=http://localhost:3002
    depends_on:
      - mongo
    ports:
      - "1975:1975"

  ui:
    build: ./ui
    platform: linux/amd64
    container_name: ui
    depends_on:
      - backend
    ports:
      - "3002:3002"

volumes:
  mongo-data:
