import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/auth-provider";
import RouteGuard from "@/lib/route-guard";
import { ErrorBoundary } from "@/components/error-boundary";
import QueryProvider from "@/lib/query-provider";

// Temporarily comment out fonts due to connection issues
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "HUEAI - Quản lý tuyển sinh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <QueryProvider>
          <AuthProvider>
            <RouteGuard>
              <ErrorBoundary>
                {children}
              </ErrorBoundary>
            </RouteGuard>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
